services:
  api:
    image: ${API_IMAGE:-bookshelf-api:latest}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_URL: jdbc:postgresql://host.docker.internal:5433/bookshelf
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      JASYPT_ENCRYPTOR_PASSWORD: ${JASYPT_ENCRYPTOR_PASSWORD}
    ports:
      - "8088:8088"

  mail-dev:
    container_name: bookshelf-mail-dev
    image: maildev/maildev:latest
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "1080:1080"
    environment:
      - MAILDEV_WEB_USER=${MAIL_USERNAME}
      - MAILDEV_WEB_PASS=${MAIL_PASSWORD}
      - MAILDEV_SMTP_PORT=1025
      - MAILDEV_WEB_PORT=1080